apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ecommerce-backend-policy
  labels:
    app.kubernetes.io/name: ecommerce
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: ecommerce-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ecommerce-frontend
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.database.range }}
    ports:
    - protocol: TCP
      port: 5432
  - to:
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53