# Image settings
frontend:
  image:
    repository: ${frontend_image_repo}
    tag: ${frontend_image_tag}
  replicaCount: 3

backend:
  image:
    repository: ${backend_image_repo}
    tag: ${backend_image_tag}
  replicaCount: 3

# Database configuration
database:
  host: "${db_host}"
  port: "${db_port}"
  name: "${db_name}"
  range: "${db_ip_range}/${db_ip_prefix}"

# Service Account
serviceAccount:
  name: "ecommerce-ksa"
  gcpServiceAccount: "${gcp_service_account}"
